### ISSUE TITLE
What if a json field has name `type` ?

### ISSUE THREAD

**Issue by pivdets** [janestreet/ppx_yojson_conv#2]
I'm trying to create an OCaml type to deserialize a json string:

```json
{
  "pages": 1,
  "data": [
      {
          "SCode": "00006",
          "RDate": "\/Date(1577721600000)\/",
          "TypeCode": "1",
          "Type": "Normal"
      },
      ...
        ],
  "dataUrl": "http://datainterface3.aws.com/pi/ZLCCMX/GetZL"
}
```

With the OCaml type

```ocaml
type t1 = {
  scode : string;
  rdate : string;
  typecode : string;
  type : string;
}
```

Well, when I tried to type `type` in VSCode, I got the error:

<img width="434" alt="image" src="https://user-images.githubusercontent.com/37371804/93082501-9f4e8400-f6c3-11ea-9c01-40572bee22ce.png">

**Comment by xclerc** [comment]
Could you double check whether the following (from [here](https://github.com/janestreet/ppx_yojson_conv/blob/master/README.org)) fixes the issue for you?

```
type t1 = {
  scode : string;
  rdate : string;
  typecode : string;
  type_ : string [@key "type"];
}
```
